
namespace Rendering;

public static class ImGuiKeyMapping
{
    /*
    public static ImGuiMouseButton AsImGuiMouseButton(this MouseButton aMouseButton)
    {
        switch(aMouseButton)
        {
            case MouseButton.Left:
                return ImGuiMouseButton.Left;
            case MouseButton.Right:
                return ImGuiMouseButton.Right;
            case MouseButton.Middle:
                return ImGuiMouseButton.Middle;
            default:
                throw new ArgumentOutOfRangeException(nameof(aMouseButton), aMouseButton, null);
        }
    }
    public static ImGuiKey AsImGuiKey(this KeyboardKey aKey)
    {
        switch (aKey)
        {
            default:
                return ImGuiKey.F24;
            case KeyboardKey.Space:
                return ImGuiKey.Space;
            case KeyboardKey.Apostrophe:
                return ImGuiKey.Apostrophe;
            case KeyboardKey.Comma:
                return ImGuiKey.Comma;
            case KeyboardKey.Minus:
                return ImGuiKey.Minus;
            case KeyboardKey.Period:
                return ImGuiKey.Period;
            case KeyboardKey.Slash:
                return ImGuiKey.Slash;
            case KeyboardKey.Alpha0:
                return ImGuiKey._0;
            case KeyboardKey.Alpha1:
                return ImGuiKey._1;
            case KeyboardKey.Alpha2:
                return ImGuiKey._2;
            case KeyboardKey.Alpha3:
                return ImGuiKey._3;
            case KeyboardKey.Alpha4:
                return ImGuiKey._4;
            case KeyboardKey.Alpha5:
                return ImGuiKey._5;
            case KeyboardKey.Alpha6:
                return ImGuiKey._6;
            case KeyboardKey.Alpha7:
                return ImGuiKey._7;
            case KeyboardKey.Alpha8:
                return ImGuiKey._8;
            case KeyboardKey.Alpha9:
                return ImGuiKey._9;
            case KeyboardKey.SemiColon:
                return ImGuiKey.Semicolon;
            case KeyboardKey.Equal:
                return ImGuiKey.Equal;
            case KeyboardKey.A:
                return ImGuiKey.A;
            case KeyboardKey.B:
                return ImGuiKey.B;
            case KeyboardKey.C:
                return ImGuiKey.C;
            case KeyboardKey.D:
                return ImGuiKey.D;
            case KeyboardKey.E:
                return ImGuiKey.E;
            case KeyboardKey.F:
                return ImGuiKey.F;
            case KeyboardKey.G:
                return ImGuiKey.G;
            case KeyboardKey.H:
                return ImGuiKey.H;
            case KeyboardKey.I:
                return ImGuiKey.I;
            case KeyboardKey.J:
                return ImGuiKey.J;
            case KeyboardKey.K:
                return ImGuiKey.K;
            case KeyboardKey.L:
                return ImGuiKey.L;
            case KeyboardKey.M:
                return ImGuiKey.M;
            case KeyboardKey.N:
                return ImGuiKey.N;
            case KeyboardKey.O:
                return ImGuiKey.O;
            case KeyboardKey.P:
                return ImGuiKey.P;
            case KeyboardKey.Q:
                return ImGuiKey.Q;
            case KeyboardKey.R:
                return ImGuiKey.R;
            case KeyboardKey.S:
                return ImGuiKey.S;
            case KeyboardKey.T:
                return ImGuiKey.T;
            case KeyboardKey.U:
                return ImGuiKey.U;
            case KeyboardKey.V:
                return ImGuiKey.V;
            case KeyboardKey.W:
                return ImGuiKey.W;
            case KeyboardKey.X:
                return ImGuiKey.X;
            case KeyboardKey.Y:
                return ImGuiKey.Y;
            case KeyboardKey.Z:
                return ImGuiKey.Z;
            case KeyboardKey.LeftBracket:
                return ImGuiKey.LeftBracket;
            case KeyboardKey.Backslash:
                return ImGuiKey.Backslash;
            case KeyboardKey.RightBracket:
                return ImGuiKey.RightBracket;
            case KeyboardKey.GraveAccent:
                return ImGuiKey.GraveAccent;
            case KeyboardKey.Escape:
                return ImGuiKey.Escape;
            case KeyboardKey.Enter:
                return ImGuiKey.Enter;
            case KeyboardKey.Tab:
                return ImGuiKey.Tab;
            case KeyboardKey.Backspace:
                return ImGuiKey.Backspace;
            case KeyboardKey.Insert:
                return ImGuiKey.Insert;
            case KeyboardKey.Delete:
                return ImGuiKey.Delete;
            case KeyboardKey.Right:
                return ImGuiKey.RightArrow;
            case KeyboardKey.Left:
                return ImGuiKey.LeftArrow;
            case KeyboardKey.Down:
                return ImGuiKey.DownArrow;   
            case KeyboardKey.Up:
                return ImGuiKey.UpArrow;
            case KeyboardKey.PageUp:
                return ImGuiKey.PageUp;
            case KeyboardKey.PageDown:
                return ImGuiKey.PageDown;
            case KeyboardKey.Home:
                return ImGuiKey.Home;
            case KeyboardKey.End:
                return ImGuiKey.End;
            case KeyboardKey.CapsLock:
                return ImGuiKey.CapsLock;
            case KeyboardKey.ScrollLock:
                return ImGuiKey.ScrollLock;
            case KeyboardKey.NumLock:
                return ImGuiKey.NumLock;
            case KeyboardKey.PrintScreen:
                return ImGuiKey.PrintScreen;
            case KeyboardKey.Pause:
                return ImGuiKey.Pause;
            case KeyboardKey.F1:
                return ImGuiKey.F1;
            case KeyboardKey.F2:
                return ImGuiKey.F2;
            case KeyboardKey.F3:
                return ImGuiKey.F3;
            case KeyboardKey.F4:
                return ImGuiKey.F4;
            case KeyboardKey.F5:
                return ImGuiKey.F5;
            case KeyboardKey.F6:
                return ImGuiKey.F6;
            case KeyboardKey.F7:
                return ImGuiKey.F7;
            case KeyboardKey.F8:
                return ImGuiKey.F8;
            case KeyboardKey.F9:
                return ImGuiKey.F9;
            case KeyboardKey.F10:
                return ImGuiKey.F10;
            case KeyboardKey.F11:
                return ImGuiKey.F11;
            case KeyboardKey.F12:
                return ImGuiKey.F12;
            case KeyboardKey.F13:
                return ImGuiKey.F13;
            case KeyboardKey.F14:
                return ImGuiKey.F14;
            case KeyboardKey.F15:
                return ImGuiKey.F15;
            case KeyboardKey.F16:
                return ImGuiKey.F16;
            case KeyboardKey.F17:
                return ImGuiKey.F17;
            case KeyboardKey.F18:
                return ImGuiKey.F18;
            case KeyboardKey.F19:
                return ImGuiKey.F19;
            case KeyboardKey.F20:
                return ImGuiKey.F20;
            case KeyboardKey.F21:
                return ImGuiKey.F21;
            case KeyboardKey.F22:
                return ImGuiKey.F22;
            case KeyboardKey.F23:
                return ImGuiKey.F23;
            case KeyboardKey.F24:
                return ImGuiKey.F24;
            case KeyboardKey.F25:
                return ImGuiKey.F24;
            case KeyboardKey.Numpad0:
                return ImGuiKey.Keypad0;
            case KeyboardKey.Numpad1:
                return ImGuiKey.Keypad1;
            case KeyboardKey.Numpad2:
                return ImGuiKey.Keypad2;
            case KeyboardKey.Numpad3:
                return ImGuiKey.Keypad3;
            case KeyboardKey.Numpad4:
                return ImGuiKey.Keypad4;
            case KeyboardKey.Numpad5:
                return ImGuiKey.Keypad5;
            case KeyboardKey.Numpad6:
                return ImGuiKey.Keypad6;
            case KeyboardKey.Numpad7:
                return ImGuiKey.Keypad7;
            case KeyboardKey.Numpad8:
                return ImGuiKey.Keypad8;
            case KeyboardKey.Numpad9:
                return ImGuiKey.Keypad9;
            case KeyboardKey.NumpadDecimal:
                return ImGuiKey.KeypadDecimal;
            case KeyboardKey.NumpadDivide:
                return ImGuiKey.KeypadDivide;
            case KeyboardKey.NumpadMultiply:
                return ImGuiKey.KeypadMultiply;
            case KeyboardKey.NumpadSubtract:
                return ImGuiKey.KeypadSubtract;
            case KeyboardKey.NumpadAdd:
                return ImGuiKey.KeypadAdd;
            case KeyboardKey.NumpadEnter:
                return ImGuiKey.KeypadEnter;
            case KeyboardKey.NumpadEqual:
                return ImGuiKey.KeypadEqual;
            case KeyboardKey.LeftShift:
                return ImGuiKey.ModShift;
            case KeyboardKey.LeftControl:
                return ImGuiKey.ModCtrl;
            case KeyboardKey.LeftAlt:
                return ImGuiKey.ModAlt;
            case KeyboardKey.LeftSuper:
                return ImGuiKey.ModSuper;
            case KeyboardKey.RightShift:
                return ImGuiKey.ModShift;
            case KeyboardKey.RightControl:
                return ImGuiKey.ModCtrl;
            case KeyboardKey.RightAlt:
                return ImGuiKey.ModAlt;
            case KeyboardKey.RightSuper:
                return ImGuiKey.ModSuper;
            case KeyboardKey.Menu:
                return ImGuiKey.Menu;
        }
    }*/
}